print('Hello world!')
print('What is your name?')
name = input()
print('Nice to meet you '+ name)
print('The lenght of your name is ' + str(len(name)))
print('What is your age?')
age = int(input('>'))
print('You will be ' + str(age+1) + ' next year.')